### PR TITLE
Ensure that default file/protocol handlers are re-installed after updating.

### LINKED ISSUE #791: torrent handler registration broken? (windows)
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
v 0.11.0 (0.96.1)

**What operating system and version?**
Windows 10 Pro x64

**What did you do?**
Click on magnet link (tried with and without using the toggle)

**What did you expect to happen?**
Expected the browser to ask to open with webtorrent-desktop (at least show it as an option)

**What actually happened?**
Webtorrent-desktop wasn't in the "open with" app list (for both magnet and stream-magnet). Torrent files (.torrent) weren't registered properly either (still defaulted to my other torrent client).

### PR DESCRIPTION
**Pull request by bnjmnt4n**
Previously, they were only installed when the preference was changed. This caused the handlers to point to non-existing files after updates occurred and older versions were removed by Squirrel.

Closes #791, #911.

### CODE REVIEW

**Comment by demoneaux** [comment]
Also, it seems weird that `state.js` is in the `renderer` folder, when it is called by both the `renderer` and `main` processes. Also, I think `migrations.js` belongs in the `main` folder, as it is typically only called to migrate updates by the main process. Maybe we should check which process it is in to decide which code to call?

File: src/renderer/lib/migrations.js [hunk 1]
```diff
@@ -43,10 +43,23 @@ function run (state) {
...
+
   // Config is now on the new version
   state.saved.version = config.APP_VERSION
 }
 
+// Whenever the app is updated,  re-install default handlers if the user has
+// enabled them.
+function installHandlers (saved) {
+  if (saved.prefs.isFileHandler) {
+    const handlers = require('../../main/handlers')
```
Comment (dcposch) [inline src/renderer/lib/migrations.js]: I don't think you can do this from the renderer process.

You have to use `ipcRenderer` to tell the main process to reinstall the handlers.

**Comment by demoneaux** [comment]
@dcposch I believe that currently `state.js` is run on both renderer and main processes, as it is loaded in the main process in order to restore window bounds.

**Comment by feross** [comment]
> I believe that currently state.js is run on both renderer and main processes, as it is loaded in the main process in order to restore window bounds.

You're right. `state.js` is required in both processes at the moment. That came in with the bound restoration change. I added a change in #995 that makes migrations only run once in the renderer (for perf, and bug prevention). `state.save()` should never be called from the main process, or we'll have serious problems. Not sure what the cleanest solution is here.

**Comment by demoneaux** [comment]
@feross I'll try to rebase on `master` and change the code to account for #773, which I hadn't seen before doing this PR.

**Comment by demoneaux** [comment]
@feross for now I've just set up the IPC renderer to install the handlers after every update. I'll look into #773 in the future.

**Comment by demoneaux** [comment]
Any updates?

**Review by DiegoRBaquero — APPROVED** [review]
